name: st_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  google_maps_flutter: ^2.10.0
  firebase_auth: ^5.3.4
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^5.6.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
